### ISSUE TITLE
Compile error: collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by ways** [djleven/opendrums#2]
Hi

I know this is an old project, but it's just what I've been looking for.

Attempting to compile on ubuntu 17.04 I get this:

```
opendrums-master$ make
g++ -c -o main.o drums.cpp `pkg-config --cflags sdl ` -ansi -pedantic -Werror -Wall
g++ -c -o display.o display.cpp `pkg-config --cflags sdl ` -ansi -pedantic -Werror -Wall
g++ -c -o sound.o sound.cpp `pkg-config --cflags sdl ` -ansi -pedantic -Werror -Wall
g++ `pkg-config --libs sdl ` -lSDL_mixer -lGL -lGLU -o out main.o display.o sound.o
main.o: In function `main':
drums.cpp:(.text+0x5e): undefined reference to `SDL_Init'
drums.cpp:(.text+0x9e): undefined reference to `SDL_Quit'
drums.cpp:(.text+0xb0): undefined reference to `SDL_JoystickOpen'
drums.cpp:(.text+0xef): undefined reference to `SDL_JoystickName'
drums.cpp:(.text+0x12c): undefined reference to `SDL_JoystickEventState'
drums.cpp:(.text+0x1f0): undefined reference to `SDL_PollEvent'
drums.cpp:(.text+0x272): undefined reference to `SDL_GetTicks'
drums.cpp:(.text+0x290): undefined reference to `SDL_GetTicks'
drums.cpp:(.text+0x29d): undefined reference to `SDL_Delay'
drums.cpp:(.text+0x2b3): undefined reference to `SDL_JoystickClose'
display.o: In function `Display::~Display()':
display.cpp:(.text+0x25): undefined reference to `gluDeleteQuadric'
display.o: In function `Display::initialize(int, int, int, int)':
display.cpp:(.text+0x71): undefined reference to `SDL_SetVideoMode'
display.cpp:(.text+0x8d): undefined reference to `SDL_WM_SetCaption'
display.cpp:(.text+0x97): undefined reference to `glShadeModel'
display.cpp:(.text+0xac): undefined reference to `glClearColor'
display.cpp:(.text+0xbb): undefined reference to `glHint'
display.cpp:(.text+0xc8): undefined reference to `glClearDepth'
display.cpp:(.text+0xd2): undefined reference to `glEnable'
display.cpp:(.text+0xdc): undefined reference to `glDepthFunc'
display.cpp:(.text+0xf5): undefined reference to `gluNewQuadric'
display.cpp:(.text+0x115): undefined reference to `gluQuadricNormals'
display.cpp:(.text+0x124): undefined reference to `glHint'
display.cpp:(.text+0x12e): undefined reference to `glEnable'
display.cpp:(.text+0x138): undefined reference to `glEnable'
display.cpp:(.text+0x14e): undefined reference to `glLightfv'
display.cpp:(.text+0x164): undefined reference to `glLightfv'
display.cpp:(.text+0x17a): undefined reference to `glLightfv'
display.cpp:(.text+0x184): undefined reference to `glEnable'
display.o: In function `Display::render()':
display.cpp:(.text+0x1dc): undefined reference to `glClearColor'
display.cpp:(.text+0x1e6): undefined reference to `glClear'
display.cpp:(.text+0x1eb): undefined reference to `glLoadIdentity'
display.cpp:(.text+0x224): undefined reference to `glTranslatef'
display.cpp:(.text+0x241): undefined reference to `glRotatef'
display.cpp:(.text+0x2ca): undefined reference to `glTranslatef'
display.cpp:(.text+0x2f4): undefined reference to `glColor3fv'
display.cpp:(.text+0x32a): undefined reference to `gluDisk'
display.cpp:(.text+0x3aa): undefined reference to `glTranslatef'
display.cpp:(.text+0x451): undefined reference to `SDL_GL_SwapBuffers'
display.o: In function `Display::resize(int, int)':
display.cpp:(.text+0x49f): undefined reference to `glViewport'
display.cpp:(.text+0x4a9): undefined reference to `glMatrixMode'
display.cpp:(.text+0x4ae): undefined reference to `glLoadIdentity'
display.cpp:(.text+0x4f9): undefined reference to `gluPerspective'
display.cpp:(.text+0x503): undefined reference to `glMatrixMode'
display.cpp:(.text+0x508): undefined reference to `glLoadIdentity'
sound.o: In function `Sound::~Sound()':
sound.cpp:(.text+0x8c): undefined reference to `Mix_FreeChunk'
sound.cpp:(.text+0x97): undefined reference to `Mix_CloseAudio'
sound.o: In function `Sound::initialize()':
sound.cpp:(.text+0xbf): undefined reference to `Mix_OpenAudio'
sound.cpp:(.text+0xcd): undefined reference to `SDL_GetError'
sound.cpp:(.text+0x125): undefined reference to `SDL_RWFromFile'
sound.cpp:(.text+0x132): undefined reference to `Mix_LoadWAV_RW'
sound.cpp:(.text+0x15b): undefined reference to `SDL_GetError'
sound.o: In function `Sound::play_sound(int)':
sound.cpp:(.text+0x1d6): undefined reference to `Mix_PlayChannelTimed'
collect2: error: ld returned 1 exit status
Makefile:31: recipe for target 'out' failed
make: *** [out] Error 1

```
